openapi: 3.0.0
info:
  title: Company API
  version: 1.0.0
  description: API for managing companies
paths:
  /api/companies:
    get:
      summary: Get all companies
      description: Retrieve a list of all companies.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          description: ID of the company
        name:
          type: string
          description: Name of the company
